# Generated by Django 3.2.7 on 2021-11-15 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_alter_transaction_assessed_by'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibraryProcessType',
            new_name='LibraryProcessTypes',
        ),
    ]
