# Generated by Django 3.2.7 on 2021-11-16 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_rename_libraryprocesstype_libraryprocesstypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAgencyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='agency_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
