# Generated by Django 3.2.7 on 2022-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_formversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='formversions',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
