# Generated by Django 3.2.6 on 2021-08-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_author_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
