# Generated by Django 3.2.6 on 2021-08-08 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed_docs', models.DateField()),
                ('date_of_assessment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('landline', models.CharField(max_length=15)),
                ('cellphone', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='cdw',
            name='docs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='frontend.docs'),
        ),
        migrations.AddField(
            model_name='worker',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='frontend.workerdetails'),
        ),
    ]
