# Generated by Django 3.2.6 on 2021-08-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210808_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdsProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.IntegerField()),
                ('upload_by_id', models.IntegerField()),
            ],
            options={
                'db_table': 'pds_province',
            },
        ),
        migrations.CreateModel(
            name='PdsCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('status', models.IntegerField()),
                ('upload_by_id', models.IntegerField()),
                ('prov_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.pdsprovince')),
            ],
            options={
                'db_table': 'pds_city',
            },
        ),
        migrations.CreateModel(
            name='PdsBarangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('upload_by_id', models.IntegerField()),
                ('city_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.pdscity', to_field='code')),
            ],
            options={
                'db_table': 'pds_barangay',
            },
        ),
    ]
