# Generated by Django 3.2.6 on 2021-08-08 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0008_pdsbarangay_pdscity_pdsprovince'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdetails',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgdetails',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orgdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by_org_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgtype',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='org_type_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
