# Generated by Django 3.2.7 on 2021-11-13 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.librarybarangay')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.librarytypes')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.libraryservices')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='org_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(null=True)),
                ('date_complete_docs', models.DateField(null=True)),
                ('date_assessed', models.DateField(null=True)),
                ('date_endorsed', models.DateField(null=True)),
                ('date_returned', models.DateField(null=True)),
                ('assessed_by', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('last', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.libraryprocess')),
                ('process_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.libraryprocesstype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.librarystatus')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.IntegerField(default=2)),
                ('extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.libraryextensions')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.org')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.transaction')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField(null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.worker')),
                ('worker_attribute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.workerattribute')),
            ],
        ),
        migrations.CreateModel(
            name='OrgTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.org')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OrgDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField(null=True)),
                ('details_attribute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.detailsattribute')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.org')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Added', 'Added'), ('Read', 'Read'), ('Updated', 'Updated'), ('Deleted', 'Deleted')], max_length=20)),
                ('message', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date_issued', models.DateField()),
                ('date_expired', models.DateField()),
                ('validity', models.IntegerField()),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.librarylevel')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default=0, max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
