# Generated by Django 3.2.7 on 2021-11-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='assessed_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
