# Generated by Django 3.2.7 on 2021-11-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_transaction_assessed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
