# Generated by Django 3.2.7 on 2021-11-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211116_1012'),
        ('frontend', '0004_auto_20211116_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='agency_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.libraryagencytypes'),
        ),
    ]
