# Generated by Django 3.2.7 on 2021-11-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211116_1012'),
        ('frontend', '0005_org_agency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='org_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.librarytypes'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='frontend.org'),
        ),
    ]
