# Generated by Django 3.2.7 on 2021-11-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_worker_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
